services:
  - type: web
    name: ativador-smart-tv
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
